In [1]:
[[3,21,14,7,15],[],[]]

[[3, 21, 14, 7, 15], [], []]

In [6]:
import numpy
data=numpy.arange(25)
print(data)
type(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


numpy.ndarray

In [8]:
data.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
data2 = numpy.arange(27)
data2.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [19]:
data3 = numpy.asarray([[3,21,14,7,15],[],[]])
data3
type(data3)

numpy.ndarray

In [43]:
import cv2
grayscale_img = cv2.imread("/Users/joshua.nebeker/Desktop/nebs-python/files/smallgray.png", 0)
type(grayscale_img)
grayscale_img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
cv2.imwrite("newsmallgray.png", grayscale_img)

True

In [44]:
grayscale_img[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [45]:
grayscale_img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [ ]:
# for el in grayscale_img:
#     print(el) - prints elements in rows 3X5

# for el in grayscale_img.T:
#     print(el) - prints element in columns 5X3

# for el in grayscale_img.flat:
#     print(el) - prints each element 1x1